stages:
  - secrets
  - build

elixir:
  stage: secrets

  image: bitwalker/alpine-elixir:1.6.5

  script:
    - ./scripts/secret.sh

  artifacts:
    paths:
    - .env

build:
  dependencies:
    - elixir

  stage: build

  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker info

  script:
    - export SMACHE_BUILD=smache:v$CI_PIPELINEID
    - docker build -t $SMACHE_BUILD .
    - docker save $SMACHE_BUILD > $SMACHE_BUILD.tar.gz
