stages:
  - secrets
  - build

elixir:
  stage: secrets

  image: bitwalker/alpine-elixir:1.6.5

  script:
    - ./scripts/secret.sh

  artifacts:
    paths:
    - .env

build:
  dependencies:
    - elixir

  stage: build

  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker info

  script:
    - export SMACHE_BUILD=smache:v$CI_PIPELINEID
    - docker login registry.gitlab.com -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD
    - docker build -t registry.gitlab.com/selfup/$SMACHE_BUILD .
    - docker push registry.gitlab.com/selfup/$SMACHE_BUILD
