stages:
  - secrets
  - build

elixir:
  stage: secrets

  image: elixir:latest
  script:
    - ./scripts/secret.sh
    - cat .env

dind:
  dependencies:
    - elixir

  stage: build

  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker info

  script:
    - export SMACHE_BUILD=smache_v$CI_PIPELINEID
    - cat .env
    - echo $SMACHE_BUILD
