stages:
  - secrets
  - build

secrets:
  stage: secrets

  image: elixir:latest
  script:
    - ./scripts/secret.sh

build:
  dependencies:
    - secrets

  stage: docker_build

  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker info

  script:
    - export SMACHE_BUILD=smache_v$CI_PIPELINEID
    - cat .env
    - echo $SMACHE_BUILD
