build:elixir_secrets:
  image: elixir:latest
  script:
    - ./scripts/secret.sh

build:docker_build:
  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker info

  build_image:
    script:
      - export SMACHE_BUILD=smache_v$CI_PIPELINEID
      - cat .env
      - echo $SMACHE_BUILD
