image: docker:stable

build:elixir_stuff:
  image: bitwalker/alpine-elixir:1.6.5
  script:
    - ./scripts/secret.sh

services:
  - docker:dind

before_script:
  - docker info

build_image:
  script:
    - export SMACHE_BUILD=smache_v$CI_PIPELINEID
    - cat .env
    - echo $SMACHE_BUILD
