stages:
  - secrets
  - build

elixir:
  stage: secrets

  image: bitwalker/alpine-elixir:1.7.3

  script:
    - export VERSION=0.0.$CI_PIPELINE_IID
    - export UPLINK_NODE=nonode@nohost
    - ./scripts/test.sh
    - ./scripts/secret.sh

  artifacts:
    paths:
      - .env

build_container:
  only:
    refs:
      - master

  dependencies:
    - elixir

  stage: build

  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker info

  script:
    - export VERSION=0.0.$CI_PIPELINE_IID
    - export SMACHE_BUILD=smache:v$CI_PIPELINE_IID
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/selfup/$SMACHE_BUILD .
    - docker push registry.gitlab.com/selfup/$SMACHE_BUILD
