stages:
  - elixir_secrets
  - docker_build

elixir_secrets:
  stage: elixir_secrets

  image: elixir:latest
  script:
    - ./scripts/secret.sh

docker_build:
  dependencies:
    - elixir_secrets

  stage: docker_build

  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker info

  script:
    - export SMACHE_BUILD=smache_v$CI_PIPELINEID
    - cat .env
    - echo $SMACHE_BUILD
