version: '3.1'

services:
  mitigator:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "4000:4000"
    environment:
      - UPLINK=true
      - VIRTUAL_MITIGATOR=true
      - MITIGATOR=${MITIGATOR}

  one:
    depends_on:
      - mitigator
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1234:4000"
    environment:
      - MITIGATOR=${MITIGATOR}

  two:
    depends_on:
      - mitigator
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1235:4000"
    environment:
      - MITIGATOR=${MITIGATOR}


  three:
    depends_on:
      - mitigator
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1236:4000"
    environment:
      - MITIGATOR=${MITIGATOR}

  four:
    depends_on:
      - mitigator
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1237:4000"
    environment:
      - MITIGATOR=${MITIGATOR}

  