version: '3.1'

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "4000:4000"
    volumes:
      - /tmp:/tmp
    environment:
      - MIX_ENV=prod
      - PORT=4000
