version: '3.1'

services:
  prod:
    build:
      context: .
      dockerfile: Dock.smache.Dockerfile
    command: bash -c "elixir rel/vm_args.exs && _build/prod/rel/smache/bin/smache foreground"
    ports:
      - "4000:4000"
    volumes:
      - /tmp:/tmp
    environment:
      - MIX_ENV=prod
      - PORT=4000
