version: '3.1'

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/smache foreground
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4000
