version: '3.1'

services:
  release:
    build:
      context: .
      dockerfile: Docker.erl.release.Dockerfile
    command: /bin/echo 'done'
    volumes:
      - .:/opt/app
    env_file:
      - .env
