version: '3.1'

services:
  smache_one:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1234:4000"
    volumes:
    - smache_mnt:/mnt

  smache_two:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1235:4000"
    volumes:
    - smache_mnt:/mnt

  smache_three:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1236:4000"
    volumes:
    - smache_mnt:/mnt

  smache_four:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1237:4000"
    volumes:
    - smache_mnt:/mnt

  