version: '3.1'

services:
  one:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1234:4000"
    environment:
      - UPLINK=true
      - UPLINK_NODE=${UPLINK_NODE}

  two:
    depends_on:
      - one
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1235:4000"
    environment:
      - UPLINK_NODE=${UPLINK_NODE}

  three:
    depends_on:
      - one
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1236:4000"
    environment:
      - UPLINK_NODE=${UPLINK_NODE}

  four:
    depends_on:
      - one
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1237:4000"
    environment:
      - UPLINK_NODE=${UPLINK_NODE}

  