version: '3.1'

services:
  mitigator:
    build:
      context: .
      dockerfile: Dock.mitigator.Dockerfile
    command: /opt/bin/mitigator
    ports:
      - "8081:8081"
    volumes:
      - .:/opt/app
