version: '3.1'

services:
  nginx-proxy:
    image: "jwilder/nginx-proxy"
    logging:
      driver: none
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  smachenode:
    depends_on:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=localhost
      - UPLINK_NODE=smachenode
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
  smacheworkers:
    depends_on:
      - smachenode
    links:
      - smachenode
    environment:
      - VIRTUAL_HOST=localhost
      - UPLINK_NODE=smachenode
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
