version: '3.1'

services:
  lb:
    image: "jwilder/nginx-proxy"
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  uplink:
    depends_on:
      - lb
    environment:
      - VIRTUAL_HOST=localhost
      - UPLINK_NODE=uplink
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
  downlink:
    depends_on:
      - uplink
    links:
      - uplink
    environment:
      - VIRTUAL_HOST=localhost
      - UPLINK_NODE=uplink
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
