version: '3.1'

services:
  prod:
    build:
      context: .
      dockerfile: Dock.smache.Dockerfile
    command: ./bin/smache foreground
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4000
  pubsub_registry:
    build:
      context: .
      dockerfile: Dock.pubsub.Dockerfile
    command: ./bin/pubsub_registry foreground
    ports:
      - "4001:4001"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4001
  mitigator:
    build:
      context: .
      dockerfile: Dock.mitigator.Dockerfile
    command: /opt/bin/mitigator
    ports:
      - "8081:8081"
    volumes:
      - .:/opt/app
