version: '3.1'

services:
  mitigator:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1233:4000"
    enviornment:
      - YO=true

  one:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1234:4000"

  two:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1235:4000"

  three:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1236:4000"

  four:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./rel/boot.sh"]
    ports:
      - "1237:4000"

  