version: '3.1'

services:
  mitigator:
    links:
      - prod1
      - prod2
    build:
      context: .
      dockerfile: Dock.mitigator.Dockerfile
    command: /opt/bin/mitigator
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    volumes:
      - .:/opt/app
  registry:
    depends_on:
      - mitigator
    build:
      context: .
      dockerfile: Dock.registry.Dockerfile
    command: ./bin/registry foreground
    ports:
      - "4001:4001"
    volumes:
      - .:/opt/app
    environment:
      - PORT=4001
  prod1:
    build:
      context: .
      dockerfile: Dock.smache.Dockerfile
    command: ./bin/smache foreground
    ports:
      - "1234:4000"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4000
  prod2:
    build:
      context: .
      dockerfile: Dock.smache.Dockerfile
    command: ./bin/smache foreground
    ports:
      - "1235:4000"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4000
