version: '3.1'

services:
  registry:
    build:
      context: .
      dockerfile: Dock.registry.Dockerfile
    command: ./bin/registry foreground
    ports:
      - "4001:4001"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4001
