version: '3.1'

services:
  uplink:
    environment:
      - UPLINK_NODE=uplink
    image: registry.gitlab.com/selfup/smache:latest
    command: ['./rel/boot.sh']
  downlink:
    depends_on:
      - uplink
    links:
      - uplink
    environment:
      - UPLINK_NODE=uplink
    image: registry.gitlab.com/selfup/smache:latest
    command: ['./rel/boot.sh']
